version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: hrmis_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    command: celery -A config worker -l info
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    command: celery -A config beat -l info
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis

volumes:
  postgres_data: