# docker-compose.yml

version: "3.8"
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backend:
    build:
      context: ./djtest
      dockerfile: Dockerfile
    container_name: django-backend
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./djtest:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - redis

  celery:
    build:
      context: ./djtest
      dockerfile: Dockerfile
    container_name: celery-worker
    command: celery -A djtest worker --loglevel=info
    volumes:
      - ./djtest:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - backend

  frontend:
    build:
      context: ./reactnote
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  redis-data:
